[project]
name = "mule"
version = "2025.10.1"
description = "API for interacting with UM output files"
readme = "README.md"
requires-python = ">=3.12.9"
dependencies = [
    "ruff==0.12.1",
    "shellcheck-py==0.10.0.1",
]
