---
name: CI
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions: read-all

jobs:
  build-test-mule:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.12', '3.13', '3.14']
        numpy-version: ['1.26.4', '2.3.4']
        exclude:
            - python-version: '3.13'
              numpy-version: '1.26.4'
            - python-version: '3.14'
              numpy-version: '1.26.4'

    steps:
      - name: Checkout Mule
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install Python Dependencies ${{ matrix.numpy-version }}
        run: |
          pip install setuptools
          pip install six
          pip install numpy==${{ matrix.numpy-version }}
      - name: Build python-${{ matrix.python-version }}_numpy-${{ matrix.numpy-version }}
        run: |
          ./admin/install_mule.sh ./_build/lib ./_build/bin
      - name: Test python-${{ matrix.python-version }}_numpy-${{ matrix.numpy-version }}
        run: |
          cd _build/lib
          for name in ./*; do
            python -m unittest discover -v ${name##*/}.tests
          done
