---
name: CI
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions: read-all

jobs:
  build-test-mule:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.12', '3.13', '3.14']
        numpy-version: ['1.26.4', '2.3.4']
        exclude:
            - python-version: '3.13'
              numpy-version: '1.26.4'
            - python-version: '3.14'
              numpy-version: '1.26.4'

    steps:
      - name: Checkout Mule
        uses: actions/checkout@v6
        with:
          path: mule
      - name: Checkout Shumlib
        uses: actions/checkout@v6
        with:
          repository: "MetOffice/shumlib"
          path: shumlib
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install Python Dependencies ${{ matrix.numpy-version }}
        run: |
          pip install setuptools
          pip install six
          pip install numpy==${{ matrix.numpy-version }}
      - name: Install shumlib
        working-directory: ${GITHUB_WORKSPACE}/shumlib
        run: |
          echo "Compiling shumlib using $(gfortran --version)"
          make -f ./make/vm-x86-gfortran-gcc.mk check
      - name: Install Mule with python-${{ matrix.python-version }}_numpy-${{ matrix.numpy-version }}
        working-directory: ${GITHUB_WORKSPACE}/mule
        run: |
          ./admin/install_mule.sh --spiral_lib --packing_lib \
                                  --shumlib_path $GITHUB_WORKSPACE/shumlib/build/vm-x86-gfortran-gcc \
                                  ./_build/lib ./_build/bin
      - name: Test Mule with python-${{ matrix.python-version }}_numpy-${{ matrix.numpy-version }}
        working-directory: ${GITHUB_WORKSPACE}/mule/_build/lib
        run: |
          for name in ./*; do
            python -m unittest discover -v ${name##*/}.tests
          done
