---
name: Docs

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'mule/docs/**'
      - '.github/workflows/docs.yaml'
  workflow_dispatch:

permissions: read-all

jobs:

  build-and-deploy-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync && uv pip install ./mule ./um_utils

      - name: Build mule docs
        run: uv run make clean html --directory ./mule/docs
        working-directory: ${{ github.workspace }}

      - name: Build um_utils docs
        run: uv run make clean html --directory ./um_utils/docs
        working-directory: ${{ github.workspace }}

      # Deploy Steps
      - name: Copy Built Documentation
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          cp -r ./mule/docs/build/html .github/files/mule
          cp -r ./um_utils/docs/build/html .github/files/um_utils

      - name: Upload artifacts
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v4
        with:
          name: github-pages
          path: .github/files

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Minimize uv cache
        if: always()
        run: uv cache prune --ci
